### ISSUE TITLE
仕様の決定

### ISSUE THREAD

**Issue by MyskYko** [MyskYko/Miyatter#1]
ツイートの情報
 - ツイートの内容
 - 時間
 - ついたコメントの数

**Comment by myskyko** [comment]
必要な画面
 - [x] タイムライン
 - [x] ツイートを個別に見る(コメントも表示)
 - [x] ツイート作成画面
 - [x] コメント作成画面

**Comment by myskyko** [comment]
- [x] 削除機能の追加
