### ISSUE TITLE
タイムラインのレイアウトの作成

### ISSUE THREAD

**Issue by MyskYko** [MyskYko/Miyatter#2]
タイムラインのレイアウト
- [x] ヘッダー(右にツイート作成ボタン)
- [x] TableView
- [x] Cell

ツイート作成用の画面
- [x] textField
- [x] 投稿ボタン
- [x] キャンセルボタン

**Comment by myskyko** [comment]
- [ ] モデルを作った後にツイートセルのプロパティを更新するためのfuncを用意する in TweetCell
