### ISSUE TITLE
モデルの作成

### ISSUE THREAD

**Issue by MyskYko** [MyskYko/Miyatter#4]
先にviewを作ってしまいましたが、モデルの作成をします
### class Tweet
 - id (primary)
 - date
 - content

### class Comment
 - id (primary)
 - date
 - content
 - Tweet

**Comment by yukitoto** [comment]
大体いい感じ！
投稿とコメントの関係がどういう関係なのか、っていうのはおそらく正しく認識してると思うんだけど、表現を変えた方が良さげ。Realmでテーブル設計すると前やったときと少し違くなるから気をつけてドキュメント読んで見て。
参考：https://realm.io/jp/docs/swift/latest/#section-5

あとこの時点で共有するのはめっちゃ正解だね。引き続き設計の時点で不安なところがあったら全然聞いて欲しい。

**Comment by myskyko** [comment]
Linking Object の使用
### class Tweet
 - id (primary)
 - date 
 - content
 - comments (LinkingObjects)

### class Comment
 - id (primary)
 - date
 - content
 - tweet

**Comment by yukitoto** [comment]
こうかな `tweet (LinkingObjects)` を使う機会はないかもだけど

### class Tweet
 - id (primary)
 - date 
 - content
 - comments (List)

### class Comment
 - id (primary)
 - date
 - content
 - tweet (LinkingObjects)

**Comment by myskyko** [comment]
確かにコメントがツイートを持つ必要はなさそうですね

### class Tweet
 - id (primary, index)
 - date
 - content
 - comments (List)

### class Comment
 - id (primary, index)
 - date
 - content
