### ISSUE TITLE
ビューモデルの実装

### ISSUE THREAD

**Issue by MyskYko** [MyskYko/Miyatter#5]
- [x] 投稿機能
 - [x] publish subjectでビューに通知

**Comment by myskyko** [comment]
### ツイートの表示
 - [x] Tweetの配列をVariableから取得 in View
 - [x] ツイートセルのプロパティを設定するためのfuncを用意する in TweetCell
 - [x] indexPath.rowに合わせてCellにTweetをぶちこむ in View

### ツイート取得の流れ
 - [x] Realmオブジェクトを通知するtoken in ViewModel
 - [x] 通知からVariable<List<Tweet>>を時間順で取得  in ViewModel
 - [x] VariableをSubscribeしてセルの再描写
