### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by MyskYko** [MyskYko/Miyatter#9]
- [x] ツイートを単体で表示できる画面を用意
 - [x] コメントの作成画面を用意
 - [x] コメントを表示できるようにする

**Comment by MyskYko** [comment]
セクションごとに違う種類のセルを表示するために
 - [ ] DataSourceを作成 in CommentViewController
 - [ ] それに合うvariableをviewModelで用意([[Tweet] = [tweet], Results<Comment>])
 - [ ] それにバインド in CommentViewController

**Comment by myskyko** [comment]
- [x] ツイート単体で表示する画面が更新されない

**Comment by MyskYko** [comment]
- [ ] 画面遷移の向き
 - [ ] セルの選択解除
 - [ ] 作成画面を分岐を用いて統一
